---
apiVersion: v1
kind: Namespace
metadata:
  name: example-namespace
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  namespace: example-namespace
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: example-service
            port:
              number: 80
  tls:
  - hosts:
    - example.com
    secretName: ssl-secret
---

apiVersion: v1
kind: Service
metadata:
  name: example-service
  namespace: example-namespace
spec:
  selector:
    app: example-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
  namespace: example-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: example-container
        image: nginx:latest
        ports:
        - containerPort: 8080
        env:
        - name: EXAMPLE_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: example-key
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        - name: efs-storage
          mountPath: /mnt/data
      volumes:
      - name: config-volume
        configMap:
          name: app-config
      - name: efs-storage
        persistentVolumeClaim:
          claimName: efs-claim
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: example-hpa
  namespace: example-namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: example-deployment
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: example-namespace
data:
  username: bXlVc2VybmFtZQ==
  password: VGhpc0lzTm90QVNlY3VyZWRQYXNzd29yZA==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: example-namespace
data:
  example.conf: |
    key=value
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-12345678
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
  namespace: example-namespace
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
