apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ .Values.secret.data.username | quote }}
  password: {{ .Values.secret.data.password | quote }}

# ---
apiVersion: v1
kind: Secret
metadata:
  name: ssl-secret
  namespace: {{ .Release.Namespace }}
data:
  tls.crt: {{ .Values.sslsecret.tlscrt | quote }}
  tls.key: {{ .Values.sslsecret.tlskey | quote }}

